languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "CUHKstudy"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  # logo = "img/logo.png"
  description = "香港中文大学学习资源分享平台"

[params.author]
  name = "小蒋"
  image = "img/Author_icon.jpg"
  headline = "欢迎来到CUHKstudy"
  bio = "香港中文大学学习资源分享，永久免费"
  links = [
    { github = "https://github.com/VincentJiang06/cuhkstudy" },
  ]