languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "CUHKstudy"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  # logo = "img/logo.png"
  description = "cu课程资料分享"

[params.author]
  name = "小蒋"
  image = "img/Author_icon.jpg"
  headline = "欢迎来到CUHKstudy"
  bio = "CS Major，UGFN/H中文版编者"
  links = []